### ISSUE TITLE
Plugin cataloging uninstalled apps

### ISSUE THREAD

**Issue by darkliquid** [ueffel/Keypirinha-WindowsApps#10]
I uninstalled an application (which may have been sideloaded, I forget) but the catalog always includes it, even after rebuilding the catalog.

Using the plugin entry, I unsurprisingly get the following output: 
```
ERROR: Error from WindowsApps.WindowsApps.on_execute: <class 'FileNotFoundError'>: file not found: "shell:AppsFolder\53621FSApps.FluentTerminal_87x1pks76srcp!App" (initial path: "shell:AppsFolder\53621FSApps.FluentTerminal_87x1pks76srcp!App")
Traceback (most recent call last):
```

If I run the following powershell, I get no results, so the app doesn't seem to appears anywhere in any manifest, so I can't work out how it is being discovered by the plugin:
```
Get-AppxPackage | Select InstallLocation | ForEach-Object { Join-Path $_.InstallLocation AppxManifest.xml } | ForEach { Get-Content $_ } | Out-String -Stream | Select-String 'Fluent'
```

**Comment by ueffel** [comment]
Well it's not discovered. You probably launched the item in question before, so it's in the history and shows up in the catalog even though it's not cataloged by the plugin anymore.
That's a functionality of Keypirinha itself and there is only one thing plugins can do about it: Don't use the history. But that has the disadvantage, that Keypirinha does not "learn" anymore, meaning it does not remember previously executed items and ranks them better in subsequent searches. I like the learning behaviour, so I won't disable the use of history.

One thing you can do is to delete the item in question from the history, so it won't show up anymore. Just search it in Keypirinha, open the context menu via right-click and use one of the menu entries to delete the item.

![image](https://user-images.githubusercontent.com/2247384/92324371-60745a80-f041-11ea-80ac-b5be028c36f8.png)

**Comment by darkliquid** [comment]
Ahh perfect, I didn't realise this was a core keypirinha thing. Clearing this history did the trick. Thanks for your help!
