### ISSUE TITLE
Several warnings in console

### ISSUE THREAD

**Issue by mc-marcocheng** [ueffel/Keypirinha-WindowsApps#11]
This package works fine in general. But when I look into the console, I realize that this package is generating multiple warnings:

```
11:12:52.759 WARNING: WindowsApps.ModernControlPanel: App Setting: {'settings_uri': 'ms-settings:quietmomentshome', 'page_name': 'SystemSettings_QuietMoments_On_Home_Mode'} display name empty
11:12:54.250 WARNING: WindowsApps.ModernControlPanel: App Setting: {'settings_uri': 'ms-settings:batterysaver-usagedetails', 'page_name': 'SystemSettings_BatterySaver_LandingPage_UsageDetailsLink'} display name empty
11:12:59.428 WindowsApps.WindowsApps: Cataloged 37 items in 23.0 seconds
11:12:59.487 WARNING: WindowsApps.ModernControlPanel: App Setting: {'settings_uri': 'ms-settings:network-wificalling', 'page_name': 'SettingsPageNetworkWiFiCalling'} display name empty
11:13:03.715 WARNING: WindowsApps.ModernControlPanel: App Setting: {'settings_uri': 'ms-settings:signinoptions', 'page_name': 'SettingsPageAccountsManage'} display name empty
11:13:06.581 WindowsApps.ModernControlPanel: Cataloged 90 items in 30.1 seconds
````

Moreover, the time that it takes to load the package is on the slow side. Is this normal or am I missing something? How can I fix those warnings?

**Comment by ueffel** [comment]
These warnings are settings pages that are removed in newer windows 10 versions. (On my Windows 10 1909 there are no errors)
Maybe quietly ignoring these would be better.

The reason cataloging is so slow is because to properly display the apps with icon and localized name the AppManifest has to be read. The AppManifest is a XML metadata file which has to be parsed in order to extract the relevant information. That sadly takes some time, far more time than just scanning directories and finding files (like the FilesCatalog).

**Comment by mc-marcocheng** [comment]
Thanks you answering my question. I am using Windows 10 2004 fyi.
To solve this problem, I actually modified the code

from:
```
if not display_name:
    self.warn("App Setting:", setting, "display name empty")
    continue
```

to:
```
if not display_name:
    display_name = setting["page_name"].replace("_", " ").lstrip("SystemSettings").lstrip("SettingsPage").strip()
```

It may not be the best practice, but it has solved my problem.

**Comment by ueffel** [comment]
Well it's no use to display these items. They would just jump to the start page of the windows settings.
I will change
```python
if not display_name:
    self.warn("App Setting:", setting, "display name empty")
    continue
```
to
```python
if not display_name:
    self.dbg("App Setting:", setting, "display name empty")
    continue
```
but I won't make a new release because of this.
