### ISSUE TITLE
 UnicodeDecodeError

### ISSUE THREAD

**Issue by PalleV** [ueffel/Keypirinha-WindowsApps#12]
I get the following error when installing this plugin. This is both with PackageControl and manually.
Running on a Windows10 machine

** ERROR: Error from WindowsApps.WindowsApps.on_catalog: <class 'UnicodeDecodeError'>: 'charmap' codec can't decode byte 0x81 in position 106229: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\[me]\AppData\Roaming\Keypirinha\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 173, in on_catalog
  File "lib\subprocess.py", line 926, in communicate
  File "lib\encodings\cp1252.py", line 23, in decode
08:45:55.739 WindowsApps.ModernControlPanel: Cataloged 91 items in 3.9 seconds

**Comment by ueffel** [comment]
Somewhere in the output of the powershell cmdlet `Get-AppPackage` is an "ü", i think. I use german windows as well and i never encountered any apps that use umlauts in their technical name. Can your run the following in a powershell console and post the output here?
```powershell
Get-AppPackage | Out-String -Stream | Select-String -Pattern 'ü'
```
(this searches for "ü" in the same output the WindowsApps-Package fails to decode)
I would like to know which app it is, to be sure my fix works.

**Comment by PalleV** [comment]
This is the output. I have replaced your real name and street with placeholders, just in case. But the output is indeed with the u-umlaut:

`Publisher         : CN=[Your name], O=[Your name], STREET=[Your address], L=Nürnberg, S=Bayern, PostalCode=90478,`

**Comment by ueffel** [comment]
Well that does not help much because I still don't know which app this is. Can post the output of
```powershell
Get-AppPackage | Where-Object {$_.Publisher -Like '*L=Nürnberg*'}
```
here?
