### ISSUE TITLE
Not working on Windows 10 21H2 build 19044.1682

### ISSUE THREAD

**Issue by salsabilng** [ueffel/Keypirinha-WindowsApps#14]
The package is not working since I updated my windows to this build, I received this message in keypiranha console

22:24:07.127 ** ERROR: Error from WindowsApps.WindowsApps.on_catalog: <class 'OSError'>: [WinError 87] The parameter is incorrect
Traceback (most recent call last):
  File "D:\System\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 173, in on_catalog
  File "lib\subprocess.py", line 775, in __init__
  File "lib\subprocess.py", line 1178, in _execute_child

**Comment by ueffel** [comment]
I have no idea what's causing this.
According to https://bugs.python.org/issue35678 the current working directory can be too long.
Can you open the Keypirinha Console (shortcut F2) and run the following:

```python
import os; len(os.getcwd())
```

It should output `20` in your case. (Then length of `D:\System\Keypirinha`)

**Comment by ueffel** [comment]
According to https://github.com/py2exe/py2exe/issues/95 or https://github.com/MrSharkSpamBot/ShadowSharkReverseShell/issues/1 it seems to be a problem, if the Microsoft Store version of python is installed.

**Comment by salsabilng** [comment]
I'm sorry, apparently the error was caused by comodo. I reset the comodo after updating windows which made keypirinha not working properly. Thank you

**Comment by ueffel** [comment]
Thanks for reporting back.
