### ISSUE TITLE
WhatsApp does not show up

### ISSUE THREAD

**Issue by hakito** [ueffel/Keypirinha-WindowsApps#15]
I installed whatsapp desktop, but for whatever reason it does not show up.

I tried refresh catalog, but it didn't work.

**Comment by ueffel** [comment]
Any errors in the keypirinha console (Hotkey: <kbd>F2</kbd>)?
for me it works just fine if I run "Keypirinha: Refresh Catalog: WindowsApps" after installing

![image](https://github.com/ueffel/Keypirinha-WindowsApps/assets/2247384/28c7453a-21ca-46cf-bb60-9d040ee6f0a0)

**Comment by hakito** [comment]
I see the following in the log:

```
17:23:15.970 PackageControl.PackageControl: Package list loaded from file cache 'ueffel's Package Repository' (75 packages)
17:23:15.970 Apps.StartMenu: Cataloged 296 items in 0.1 seconds
17:23:16.001 FilesCatalog.FilesCatalog: Cataloging 1 profile...
17:23:17.438 Apps.EnvPath: Cataloged 881 items in 1.5 seconds
17:23:18.579 Bookmarks.Bookmarks: Referenced 763 bookmarks
17:23:24.752 ** ERROR: Error from WindowsApps.WindowsApps.on_catalog: <class 'UnicodeDecodeError'>: 'utf-8' codec can't decode byte 0x81 in position 33930: invalid start byte
Traceback (most recent call last):
  File "C:\Tools\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 176, in on_catalog
17:23:27.485 WindowsApps.ModernControlPanel: Cataloged 91 items in 11.2 seconds
```

**Comment by ueffel** [comment]
Are you sure you're using the most recent version of the package? This error looks a lot like #12, which should be fixed.
Try reinstalling via PackageControl or download the current version from here <https://github.com/ueffel/Keypirinha-WindowsApps/releases/latest> and install manually.

**Comment by hakito** [comment]
At least when I try to update I get this in the log:

```
08:34:32.644 PackageControl.PackageControl: Package up to date: Keypirinha-WindowsApps
08:34:55.280 FilesCatalog.FilesCatalog: Cataloging 1 profile...
08:34:55.384 Apps.Desktop: Cataloged 50 items in 0.1 seconds
08:34:55.488 Apps.StartMenu: Cataloged 296 items in 0.2 seconds
08:34:55.579 Apps.EnvPath: Cataloged 881 items in 0.3 seconds
08:34:55.635 Bookmarks.Bookmarks: Referenced 763 bookmarks
08:34:55.801 FilesCatalog.FilesCatalog: Profile Solutions: found 25 items in 0.5 seconds
08:34:55.801 FilesCatalog.FilesCatalog: Cataloged 25 items in 0.0 seconds
08:34:55.801 FilesCatalog.FilesCatalog: Total: 25 items found and cataloged in 0.5 seconds
08:35:00.258 ** ERROR: Error from WindowsApps.WindowsApps.on_catalog: <class 'UnicodeDecodeError'>: 'utf-8' codec can't decode byte 0x81 in position 33930: invalid start byte
Traceback (most recent call last):
  File "C:\Tools\Keypirinha\portable\Profile\InstalledPackages\WindowsApps.keypirinha-package\windowsapps.py", line 176, in on_catalog
  ```

**Comment by ueffel** [comment]
Can you open a Powershell and run this command

```pwsh
chcp 65001 >$null; Get-AppxPackage | ConvertTo-Json > $env:TEMP\out.json; echo $env:TEMP\out.json
```

and upload the file that is generated here?

It will contain the output of installed Windows Apps that the plugin uses. There must be something wrong with it on your system and I need to take a look at it to figure out wants going wrong

**Comment by hakito** [comment]
In case the log contains sensitive data I mailed it directly to you instead of uploading here.

**Comment by ueffel** [comment]
*sigh*
Powershell does not have any consistent encoding handling...
The file you mailed be is utf16-le encoded, the initial error you posted is an `ü` encoded as cp850 and read as utf-8.
Well at least I found out which installed app causes the error:

```json
        "Name":  "Smallpdf",
        "Publisher":  "CN=Smallpdf AG, O=Smallpdf AG, L=Zürich, S=Zürich, C=CH, SERIALNUMBER=CHE-461.243.982, OID.1.3.6.1.4.1.311.60.2.1.2=Zürich, OID.1.3.6.1.4.1.311.60.2.1.3=CH, OID.2.5.4.15=Private Organization",    
```

The `ü` in `Zürich` should be the problem.

I tried installing this app myself but the only SmallPDF app I found produces this for me

```json
        "Name":  "SmallpdfAG.Smallpdf",
        "Publisher":  "CN=620E293E-26F8-4693-B472-4498B3045DBF",
```

So german umlaut, no problem :/

Can you try putting this file in your InstalledPackages directory and rename it to "WindowsApps.keypirinha-package" (replace the existing file)
[WindowsApps.zip](https://github.com/ueffel/Keypirinha-WindowsApps/files/14052190/WindowsApps.zip)

It contains a slightly modified powershell call in an attempt to fix the problem.

**Comment by ueffel** [comment]
Weird. Alrighty new release is out.
