### ISSUE TITLE
system settings disabled, but still visible

### ISSUE THREAD

**Issue by stew11** [ueffel/Keypirinha-WindowsApps#17]
I configured like below:
```
[main]
item_label =
disable_settings = yes
```
but that settings are still visible:
![Zrzut ekranu 2024-11-05 162045](https://github.com/user-attachments/assets/9bfc2757-72c7-430a-b329-910a6b9d703a)

**Comment by ueffel** [comment]
These items might be in the history of keypirinha if you executed them before. Try removing them via the context menu entry `Remove from History` one by one, or use `Remove parent package from History` to remove them all.

If `disable_settings = yes` is set, they shouldn't be cataloged anymore.
A restart of keypirinha seems to be necessary, I see what I can do about that.

**Comment by stew11** [comment]
I can't remove it, because that entries are not clickable.
![Zrzut ekranu 2024-11-05 221234](https://github.com/user-attachments/assets/2a897ea0-8960-44f4-ae4a-d7487144ab09)

I tried check it on fresh Windows 10 installation over VM and it's the same.
![Zrzut ekranu 2024-11-05 222708](https://github.com/user-attachments/assets/92827ce5-cab2-4dd2-ae2c-b59710634082)

**Comment by stew11** [comment]
Excellent, it works as it should now.
Thank you very much!
