### ISSUE TITLE
powershell call might fail if user has a profile.ps1 file

### ISSUE THREAD

**Issue by Napo2k** [ueffel/Keypirinha-WindowsApps#3]
When trying to install this Keypirinha package in my machine, I found that, when my profile.ps1 file was big enough, this call

https://github.com/ueffel/Keypirinha-WindowsApps/blob/master/windowsapps.py#L125

would not yield the results that the script was expecting. In my case I make sure a bunch of stuff is installed.
This can be easily fixed by calling `powershell.exe` with the `--No-Profile` parameter

**Comment by ueffel** [comment]
`-noprofile` seems to be the correct name for the parameter. It seems reasonable to add this to the call.

**Comment by ueffel** [comment]
Feel free to reopen this issue if the new version still does not work for you.
