### ISSUE TITLE
Parsing of powershell results might fail if package details contain newline

### ISSUE THREAD

**Issue by Napo2k** [ueffel/Keypirinha-WindowsApps#4]
When parsing the results of the powershell call, 

https://github.com/ueffel/Keypirinha-WindowsApps/blob/master/windowsapps.py#L137-L141

this bit can fail if any of the resulting packages contains a newline in any of the details. In my case it was in the dependency metadata section.

**Comment by ueffel** [comment]
That's why there is the `mode con cols=512` part in the powershell call. Apparently 512 isn't big enough. 

Maybe there is some powershell magic format the output in another way to make this whole thing a bit more elegant.

**Comment by ueffel** [comment]
Feel free to reopen this issue if the new version still does not work for you.
