### ISSUE TITLE
UWP HiDPI icon support

### ISSUE THREAD

**Issue by lasgor** [ueffel/Keypirinha-WindowsApps#5]
Hi, I see Wox launcher supports HiDPI icons for UWP apps:
[https://github.com/Wox-launcher/Wox/blob/master/Plugins/Wox.Plugin.Program/Programs/UWP.cs](https://github.com/Wox-launcher/Wox/blob/master/Plugins/Wox.Plugin.Program/Programs/UWP.cs)

Perhaps you could implement this as well?

**Comment by ueffel** [comment]
For the record, i didn't see any of the windows app icon in wox. They all had the wox default icon. But had a look at the code. Apparently the `Square44x44Logo` asset size and its scaled versions work best for keypirinha. I thought that bigger asset sizes like `Square150x150Logo` would make for a better icon, but they just add a lot of unused space around the actual logo. This makes sense when displaying in the start menu as tiles to allow a bit of overlap, but not for the keypirinha icon use case.

So yeah, have a look at the 0.7.0 release. The icons should look better now :)
