### ISSUE TITLE
Support actions for Windows Apps

### ISSUE THREAD

**Issue by dpprdan** [ueffel/Keypirinha-WindowsApps#8]
Would it be possible to support [actions](http://keypirinha.com/first.html#actions) for Windows Apps? So that one could open an elevated terminal, for example? 

These are the actions available in the Windows menu/search for the [Windows Terminal](https://www.microsoft.com/store/productId/9N0DX20HK701) for example (in German):

![grafik](https://user-images.githubusercontent.com/1423562/83151657-24099800-a0fd-11ea-97c2-fa22c50af256.png)

**Comment by ueffel** [comment]
I added actions to run as admin and open the store page of the app. Check out the new version (needs a restart of keypirinha to work properly)

I really wanted to add a action to open the app-settings, but I didn't found a way to do it :/
