### ISSUE TITLE
Run apps as administrator

### ISSUE THREAD

**Issue by loligans** [ueffel/Keypirinha-WindowsApps#9]
When I try to launch Windows Terminal, I am unable to run it as an administrator.

**Comment by ueffel** [comment]
That sounds awfully vague. Can you elaborate? 

Is there no action "Run as administrator"? Is the action there but does nothing? Is there anything log in the Keypirinha: Console (Shortcut F2)?

**Comment by laurin1** [comment]
To RAA from Keypirinha, you must run Keypirinha as admin. We do it on all of our admin machines by using the registry and GPO to set the appcompatflag to RAA for keypirinha.exe, and put in startup and run with a batch file (for some reason, RAA executables will not launch without the batch file).

**Comment by ueffel** [comment]
> To RAA from Keypirinha, you must run Keypirinha as admin. We do it on all of our admin machines by using the registry and GPO to set the appcompatflag to RAA for keypirinha.exe, and put in startup and run with a batch file (for some reason, RAA executables will not launch without the batch file).

I added a new action to run any UWP Apps as Administrator from a unelevated Keypirinha in the latest version of this package.

![image](https://user-images.githubusercontent.com/2247384/87544614-0ee5ca00-c6a7-11ea-8750-3b0e126db9b8.png)
(german windows over here)

And it works fine for me

**Comment by laurin1** [comment]
Ah, I was unaware - we prefer to just RAA everything (despite what MS says). :)

**Comment by loligans** [comment]
> 
> 
> > To RAA from Keypirinha, you must run Keypirinha as admin. We do it on all of our admin machines by using the registry and GPO to set the appcompatflag to RAA for keypirinha.exe, and put in startup and run with a batch file (for some reason, RAA executables will not launch without the batch file).
> 
> I added a new action to run any UWP Apps as Administrator from a unelevated Keypirinha in the latest version of this package.
> 
> ![image](https://user-images.githubusercontent.com/2247384/87544614-0ee5ca00-c6a7-11ea-8750-3b0e126db9b8.png)
> (german windows over here)
> 
> And it works fine for me

This is what I was looking for. Would it be possible to make this the default? 

Perhaps configuring on a per-app bases?

ie. Windows Terminal is configured to always run as administrator
ie. Windows Calculator is configured (by default) to _not_ run as administrator

**Comment by ueffel** [comment]
I don't like it. It feels very hacky to me. If its really only the windows terminal your want to execute as administrator, a powershell one-liner that runs `%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe` as administrator would be a more reasonable solution. This could be included via Custom Command in keypirinha.

I don't see that one would need to run any other windows apps as administrator frequently.

**Comment by fran-f** [comment]
Starting Terminal as administrator is a bit tricky, given it's a stub executable as well. Took me some time to get it working in my [Terminal Profiles](https://github.com/fran-f/keypirinha-terminal-profiles) plug-in, which I shall *plug* here with limited shame, since it's solves the problem 😉

**Comment by ueffel** [comment]
Closing due lack of interest?
